image: python:latest

before_script:
  - apt-get update -qq && apt-get -y install mpich libfftw3-dev libhdf5-dev

test:
  script:
    - cd src
    - make -k -j 4 test_recombine test_config iotest
    # Unit tests
    - ./test_recombine
    # Standard test
    - make test_T05 | tee iotest.out
    - if grep ERROR iotest.out; then exit 1; fi
    # Self-tests
    - make test_small
    # Distributed tests
    - for i in $(seq 0 16); do
        mpirun -n 16 ./iotest --rec-set=T05 --facet-workers=$i > iotest$i.out;
        if grep ERROR iotest$i.out; then exit 1; fi;
      done
